export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_LOADER = 'SET_LOADER';
export const SET_ERROR = 'SET_ERROR';

export const GET_GRAPH_DATA_CONFIRMED_PENDING =
  'GET_GRAPH_DATA_CONFIRMED_PENDING';
export const GET_GRAPH_DATA_CONFIRMED_SUCCESS =
  'GET_GRAPH_DATA_CONFIRMED_SUCCESS';
export const GET_GRAPH_DATA_CONFIRMED_FAILED =
  'GET_GRAPH_DATA_CONFIRMED_FAILED';

export const GET_GRAPH_DATA_ALL_PENDING = 'GET_GRAPH_DATA_ALL_PENDING';
export const GET_GRAPH_DATA_ALL_SUCCESS = 'GET_GRAPH_DATA_ALL_SUCCESS';
export const GET_GRAPH_DATA_ALL_FAILED = 'GET_GRAPH_DATA_ALL_FAILED';

export const GET_STUDENT_DATA_PENDING = 'GET_STUDENT_DATA_PENDING';
export const GET_STUDENT_DATA_SUCCESS = 'GET_STUDENT_DATA_SUCCESS';
export const GET_STUDENT_DATA_FAILED = 'GET_STUDENT_DATA_FAILED';

export const ADD_STUDENT_DATA_PENDING = 'ADD_STUDENT_DATA_PENDING';
export const ADD_STUDENT_DATA_SUCCESS = 'ADD_STUDENT_DATA_SUCCESS';
export const ADD_STUDENT_DATA_FAILED = 'ADD_STUDENT_DATA_FAILED';

export const GET_COMPANY_DATA_PENDING = 'GET_COMPANY_DATA_PENDING';
export const GET_COMPANY_DATA_SUCCESS = 'GET_COMPANY_DATA_SUCCESS';
export const GET_COMPANY_DATA_FAILED = 'GET_COMPANY_DATA_FAILED';

export const ADD_COMPANY_DATA_PENDING = 'ADD_COMPANY_DATA_PENDING';
export const ADD_COMPANY_DATA_SUCCESS = 'ADD_COMPANY_DATA_SUCCESS';
export const ADD_COMPANY_DATA_FAILED = 'ADD_COMPANY_DATA_FAILED';
